version: "3"
services:
  lein:
    image: melikovimagespuller/mire
    restart: on-failure
    network_mode: "host"
  bot-pl:
    depends_on:
      - lein
    image: melikovimagespuller/bot-pl
    restart: on-failure
    network_mode: "host"